apiVersion: v1
kind: Secret
metadata:
  name: admin-secret
data:
  users: |2
    {{ htpasswd .Values.credentials.username (required "You need to set the password" .Values.credentials.password) | b64enc }}